name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests (default features)
      run: cargo test --verbose
    - name: Run tests (all features)
      run: cargo test --verbose --all-features
    - name: Build docs
      run: cargo doc --no-deps --verbose
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Check linting
      run: cargo clippy --all-targets --all-features -- -D warnings
